name: status_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  api:
    path: packages/api

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  # theme_provider: ^0.6.0
  intl: ^0.19.0
  calendar_view: ^1.4.0
  calendar_date_picker2: ^1.1.9

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^2.8.1

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 600
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
