name: status_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^2.8.1

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
          weight: 600
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
