name: api
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4

  rxdart: ^0.27.7

dev_dependencies:
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

  flutter_lints: ^5.0.0
